/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DealsNewRouteImport } from './routes/deals/new'
import { Route as DealsDealIdRouteImport } from './routes/deals/$dealId'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminParametersRouteImport } from './routes/admin/parameters'
import { Route as AdminApprovalRulesRouteImport } from './routes/admin/approval-rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewRoute = DealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealIdRoute = DealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametersRoute = AdminParametersRouteImport.update({
  id: '/admin/parameters',
  path: '/admin/parameters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalRulesRoute = AdminApprovalRulesRouteImport.update({
  id: '/admin/approval-rules',
  path: '/admin/approval-rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/approval-rules': typeof AdminApprovalRulesRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/products': typeof AdminProductsRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/approval-rules': typeof AdminApprovalRulesRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/products': typeof AdminProductsRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/approval-rules': typeof AdminApprovalRulesRoute
  '/admin/parameters': typeof AdminParametersRoute
  '/admin/products': typeof AdminProductsRoute
  '/deals/$dealId': typeof DealsDealIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/approval-rules'
    | '/admin/parameters'
    | '/admin/products'
    | '/deals/$dealId'
    | '/deals/new'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/approval-rules'
    | '/admin/parameters'
    | '/admin/products'
    | '/deals/$dealId'
    | '/deals/new'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/admin/approval-rules'
    | '/admin/parameters'
    | '/admin/products'
    | '/deals/$dealId'
    | '/deals/new'
    | '/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminApprovalRulesRoute: typeof AdminApprovalRulesRoute
  AdminParametersRoute: typeof AdminParametersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  DealsDealIdRoute: typeof DealsDealIdRoute
  DealsNewRoute: typeof DealsNewRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new': {
      id: '/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealId': {
      id: '/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof DealsDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parameters': {
      id: '/admin/parameters'
      path: '/admin/parameters'
      fullPath: '/admin/parameters'
      preLoaderRoute: typeof AdminParametersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approval-rules': {
      id: '/admin/approval-rules'
      path: '/admin/approval-rules'
      fullPath: '/admin/approval-rules'
      preLoaderRoute: typeof AdminApprovalRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminApprovalRulesRoute: AdminApprovalRulesRoute,
  AdminParametersRoute: AdminParametersRoute,
  AdminProductsRoute: AdminProductsRoute,
  DealsDealIdRoute: DealsDealIdRoute,
  DealsNewRoute: DealsNewRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
